# Generated by Django 4.0.6 on 2022-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='dateOfBirth',
            field=models.DateField(null=True),
        ),
    ]
