# Generated by Django 4.0.6 on 2022-07-09 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_login_dateofbirth'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
